# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finpulse-app
  namespace: finpulse-staging

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: finpulse-app
  template:
    metadata:
      labels:
        app: finpulse-app
    spec:
      containers:
        - name: finpulse-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          env:
            - name: BACKEND
              value: {{ .Values.backend | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: finpulse-app
  namespace: finpulse-staging
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: finpulse-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      {{- if eq .Values.serviceType "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  {{- if eq .Values.serviceType "ClusterIP" }}
  externalIPs:
    - {{ .Values.service.externalIP }}
  {{- end }}

